### ISSUE TITLE
検索でエラーがでることがある

### ISSUE THREAD

**Issue by taisukef** [code4fukui/yabamichi-checker#16]
```
TypeError: Cannot read properties of undefined (reading '0')
    at FromTo.searchRoute (file:///Users/fukuno/data/js/service/yabamichi-checker/route.js:49:33)
    at async Result.contents (file:///Users/fukuno/data/js/service/yabamichi-checker/result.js:17:18)
    at async Result.render (file:///Users/fukuno/data/js/service/yabamichi-checker/page.js:16:13)
    at async Server.<anonymous> (file:///Users/fukuno/data/js/service/yabamichi-checker/main.js:21:14)
    at async Server.#respond (https://deno.land/std@0.178.0/http/server.ts:299:18)
```

**Comment by taisukef** [comment]
keyが未設定だったかも

**Comment by taisukef** [comment]
https://github.com/code4fukui/yabamichi-checker/pull/18
起動方法、APIトークン取得方法追記
